version: '2'
volumes:
  app:
  db:
services:
  app:
    container_name: gitea-app
    restart: always
    image: gitea/gitea:${GITEA_VERSION}
    volumes:
      - ./volumes/gitea_app:/data
    ports:
      - "${GITEA_SSH_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
    environment:
      - VIRTUAL_PORT=3333
      - VIRTUAL_HOST=${GITEA_HOSTNAME}
    networks:
      - backend
      - frontend
    depends_on:
      - db
  db:
    container_name: gitea-db    
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    networks:
      - backend
    volumes:
      - ./volumes/gitea_db:/var/lib/postgresql/data

networks:
  frontend:
  backend:
